---
- hosts: all
  become: true
  tasks:
    - name: Copy zabbix package
      copy:
        src: /tmp/zabbix-release_6.0-4+ubuntu20.04_all.deb
        dest: /tmp/
    - name: Install zabbix repo from local repository
      apt:
        deb: /tmp/zabbix-release_6.0-4+ubuntu20.04_all.deb
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install zabbix agent
      apt:
        name: zabbix-agent2
        state: present

  handlers:
    - name: zabbix-agent2
      systemd:
         name: zabbix-agent2
         enabled: yes
         state: started
